news_project/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout_exit'),
    path('register/', authapp.register, name='register'),
]

news_project/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('news/<int:pk>/', mainapp.select_news, name='select_news'),

    path('comment', mainapp.comments, name='comment'),
    path('comment/add/', mainapp.create_comments, name='create_comments'),
    path('comment/remove/<int:pk>', mainapp.remove_comments, name='remove_comments'),
    path('comment/edit/<int:pk>', mainapp.update_comments, name='update_comments'),
    path('about/', mainapp.about, name='about'),
    path('favorite/', mainapp.favorite, name='favorite'),
    path('favorite/remove/<int:pk>/', mainapp.remove_favorite, name='remove_favorite'),
    path('favorite/add/<int:pk>/', mainapp.add_favorite, name='add_favorite'),
]

news_project/news_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from news_project import settings

urlpatterns = [
    path('', include('mainapp.urls', namespace='mainapp')),
    path('accounts/', include('authapp.urls', namespace='authapp')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_project/mainapp/models.py
from django.contrib.auth.models import User
from django.db import models


class News(models.Model):
    title = models.CharField(verbose_name='Заголовок', max_length=256)
    content = models.TextField(verbose_name='Контент')
    image = models.ImageField(verbose_name='Изображение', upload_to='news/%Y/%m/%d')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


class Comments(models.Model):
    class Status(models.TextChoices):
        ZERO = '0', 'Заблокирован',
        FIRST = '1', 'Опубликован',
        TWO = '2', 'Ожидает проверки'

    news = models.ForeignKey(News, verbose_name='Новость', on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    comment = models.TextField(verbose_name='Комментарий')
    status = models.CharField(verbose_name='Статус', max_length=1, choices=Status.choices, default=Status.TWO)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Favorite(models.Model):
    news = models.ForeignKey(News, verbose_name='Новость', on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранные'


class Mail(models.Model):
    theme = models.CharField(verbose_name='Тема письма', max_length=256)
    email = models.EmailField(verbose_name='Email')
    text = models.TextField(verbose_name='текст')
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.theme

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Почта'
        verbose_name_plural = 'Почта'

news_project/mainapp/forms.py
from django.forms import ModelForm

from mainapp.models import Comments, Mail


class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ('comment',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control p-3 {name} '
            item.help_text = ''

class MailForm(ModelForm):
    class Meta:
        model = Mail
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control p-3 {name} '
            item.help_text = ''

news_project/mainapp/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from mainapp.forms import CommentForm, MailForm

from mainapp.models import News, Comments, Favorite

from news_project import settings


def index(request):
    news = News.objects.all()
    paginate = Paginator(news, 1)
    print(paginate)
    page_number = request.GET.get('page')
    page_object = paginate.get_page(page_number)
    context = {
        'news': page_object,
    }
    return render(request, 'mainapp/index.html', context)


def select_news(request, pk):
    news = get_object_or_404(News, id=pk)
    comment = Comments.objects.filter(news=news, status=Comments.Status.FIRST)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid:
            form_2 = form.save(commit=False)
            form_2.user = request.user
            form_2.news = news
            form_2.save()
            return HttpResponseRedirect(reverse('mainapp:select_news', kwargs={'pk': news.id}))
    else:
        form = CommentForm

    context = {
        'title': news.title,
        'news': news,
        'comments': comment,
        'form': form,
    }
    return render(request, 'mainapp/select_news.html', context)


def comments(request):
    comment = Comments.objects.all()
    context = {
        'title': 'главная',
        'comment': comment
    }
    return render(request, 'mainapp/comment.html', context)


def create_comments(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainapp:comment'))
    else:
        form = CommentForm()
    context = {
        'title': 'добавить комментарий',
        'form': form,
    }
    return render(request, 'mainapp/add/comment.html', context)


def remove_comments(request, pk):
    comment = get_object_or_404(Comments, id=pk)
    comment.delete()
    return HttpResponseRedirect(reverse('mainapp:comment'))


def update_comments(request, pk):
    comment = get_object_or_404(Comments, id=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainapp:comment'))
    else:
        form = CommentForm(instance=comment)

    context = {
        'title': 'добавить комментарий',
        'form': form,
    }
    return render(request, 'mainapp/edit/comment.html', context)


def about(request):
    if request.method == 'POST':
        form = MailForm(request.POST)
        if form.is_valid():
            form2 = form.save(commit=False)
            message = f'От: {form2.email}, Тема: {form2.theme} \nТекст: {form2.text}\n'
            send_mail(form2.theme, message, settings.EMAIL_HOST_USER, ['crimecrew21@mail.ru'])
            if send_mail:
                form2.save()
                return HttpResponseRedirect(reverse('mainapp:about'))
    else:
        form = MailForm()
    context = {
        'title': 'братная связь',
        'form': form,
    }
    return render(request, 'mainapp/about.html', context)


def favorite(request):
    favor = Favorite.objects.filter(user=request.user)
    context = {
        'title': 'избранное',
        'favorite': favor,
    }
    return render(request, 'mainapp/favorite.html', context)

def add_favorite(request, pk):
    news = get_object_or_404(News, id=pk)
    Favorite.objects.get_or_create(
        news=news,
        user=request.user
    )
    return  HttpResponseRedirect(reverse('mainapp:index'))
def remove_favorite(request, pk):
    favor = get_object_or_404(Favorite, id=pk)
    favor.delete()
    return HttpResponseRedirect(reverse('mainapp:index'))

news_project/mainapp/templates/mainapp/about.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <h3>О нас</h3>
    <p>Отправить письмо</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-2">
            <button class="btn btn-success">
                Отправить
            </button>
        </div>
    </form>
{% endblock %}

news_project/mainapp/templates/mainapp/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title|capfirst }} | Новостной портал</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
</head>
<body>
<nav class="container navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Новости</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:about'%}">Обратная связь</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:favorite' %}">Избранное</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:logout_exit' %}">Выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:register' %}">Регистрация</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:login' %}">Авторизация</a>
                    </li>
                    <li><a href="{% url 'mainapp:comment' %}" class="dropdown-item">Добавить комментарий</a></li>
                {% endif %}
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<div class="container my-3">
    {% block content %}

    {% endblock %}
</div>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

news_project/mainapp/templates/mainapp/comment.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <h3>Коментарии</h3>
    {% for item in comment %}
        <div class="my-3">
            <h5>
            <a href="{% url 'mainapp:update_comments' item.id %}">{{ item.comment }}</a>
            </h5>
            <a href="{% url 'mainapp:remove_comments' item.id %}" class="btn btn-danger mx-3">Удалить</a>
        </div>
    {% endfor %}

{% endblock %}

news_project/mainapp/templates/mainapp/favorite.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <h1>Избранное</h1>
    <table class="table my-2 box">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название новости</th>
            <th scope="col">Действие</th>
        </tr>
        </thead>
        <tbody>
        {% for item in favorite %}
            <tr>
                <th scope="row">{{ item.id }}</th>
                <td>{{ item.news.title }}</td>
                        <td>
                <div class="row">
                    <div class="col">
                        <a href="{% url 'mainapp:select_news' item.news.id %}" class="btn btn-primary">Посмотреть
                            новость</a>
                    </div>
                    <div class="col">
                        <a href="{% url 'mainapp:remove_favorite' item.id %}" class="btn btn-danger">Удалить из
                            избранного</a>
                    </div>
                </div>
            </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

news_project/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <h3>Новости</h3>
    {% for item in news %}
        <div class="news my-3">
            <h5>{{ item.title }}</h5>
            <p>{{ item.content|linebreaks|truncatewords:23 }}</p>
            <img src="{{ item.image.url }}" alt="{{ item.title }}" class="card-img-top">
            <p>Создано: {{ item.created_at }}</p>
            <div class="d-grid gap-2">
                <div class="row">
                    <div class="d-flex justify-content-center align-content-center align-items-center flex-wrap">
                        <a href="{% url 'mainapp:select_news' item.id %}" class="btn btn-success p-3 mx-4">Перейти к
                            записи</a>



                        <a href="{% url 'mainapp:add_favorite' item.id %}" class="btn btn-success p-3">Добавить в
                            избранное</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if news.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ news.previous_page_number }}">Предыдущая</a>
                </li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">Предыдущая</a></li>
            {% endif %}
            {% for i in news.paginator.page_range %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
            {% if news.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ news.next_page_number }}">Следующая</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#">Следующая</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

news_project/mainapp/templates/mainapp/select_messages.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success">Отправить</button>
    </form>
{% endblock %}

news_project/mainapp/templates/mainapp/select_news.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <h3>{{ news.title }}</h3>
    <p>{{ news.content|linebreaks }}</p>
    <img src="{{ news.image.url }}" alt="{{ news.title }}"
         class="card-img-top">
    <hr>
    {% if user.is_authenticated %}
    <div class="comments_form my-2 p-2">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success my-2">Отправить</button>
        </form>
    </div>
    {% else %}
        <a href="{% url 'authapp:login' %}" class="btn btn-success btn-lg">Авторизоваться</a>
    {% endif %}
    <div class="comments my-3 p-2">
        <h3>Комментарии</h3>
        {% for item in comments %}
            <div class="comments">
                <h3>{{ item.user.username }}</h3>
                <hr>
                <p>{{ item.comment|linebreaksbr }}</p>
                <p class="small end"> {{ item.created_at }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}